version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm test
      - run: pwd
      
workflows:
  version: 2
  build_wf:
    jobs:
      - build
